import { NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { mkdir, writeFile } from 'fs/promises';
import path from 'path';

import { generateText } from 'ai';
import { createOpenAI } from '@ai-sdk/openai';
import { createGroq } from '@ai-sdk/groq';
import { createAnthropic } from '@ai-sdk/anthropic';
import { createGoogleGenerativeAI } from '@ai-sdk/google';
import { appConfig } from '@/config/app.config';

const openai = createOpenAI({ apiKey: process.env.OPENAI_API_KEY });
const groq = createGroq({ apiKey: process.env.GROQ_API_KEY });
const anthropic = createAnthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const google = createGoogleGenerativeAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(req: Request) {
  try {
    const { prompt, model } = await req.json() as { prompt: string; model?: string };
    if (!prompt || prompt.trim().length < 5) {
      return NextResponse.json({ error: 'Prompt is too short.' }, { status: 400 });
    }

    const modelName = model || appConfig.ai.defaultModel;
    const isAnthropic = modelName.startsWith('anthropic/');
    const isGoogle = modelName.startsWith('google/');
    const isOpenAI = modelName.startsWith('openai/');
    const modelProvider = isAnthropic
      ? anthropic
      : isOpenAI
        ? openai
        : isGoogle
          ? google
          : groq;
    const actualModel = modelName.replace(/^(anthropic|google|openai|groq)\//, '');

    const { text } = await generateText({
      model: modelProvider(actualModel),
      temperature: 0.5,
      system: `You generate single-file web apps from a prompt. \\
Return THREE fenced code blocks ONLY in this order and nothing else:\\
1) HTML codeblock tagged 'html'\\
2) CSS codeblock tagged 'css'\\
3) JS codeblock tagged 'javascript'`,
      prompt: `Build a small, self-contained web app for this request:\n${prompt}\n\nConstraints:\n- Keep it simple and functional.\n- No external CDNs; inline references only.\n- The HTML should load styles.css and script.js.\n- Add a visible H1 and a footer with "Generated by ZEN Edge".`,
    });

    const match = text.matchAll(/```(html|css|javascript)\s*([\s\S]*?)```/gi);
    let html = '', css = '', js = '';
    for (const m of match) {
      const lang = (m[1] || '').toLowerCase();
      const body = m[2] || '';
      if (lang === 'html') html = body.trim();
      else if (lang === 'css') css = body.trim();
      else if (lang === 'javascript') js = body.trim();
    }
    if (!html || !css || !js) {
      return NextResponse.json({ error: 'Model returned unexpected format.' }, { status: 500 });
    }

    const id = randomUUID();
    const baseDir = path.join(process.cwd(), 'public', 'generated', id);
    await mkdir(baseDir, { recursive: true });
    await Promise.all([
      writeFile(path.join(baseDir, 'index.html'), html, 'utf8'),
      writeFile(path.join(baseDir, 'styles.css'), css, 'utf8'),
      writeFile(path.join(baseDir, 'script.js'), js, 'utf8'),
    ]);

    const previewUrl = `/generated/${id}/index.html`;
    return NextResponse.json({ id, previewUrl });
  } catch (err: any) {
    console.error('generate-project error', err);
    return NextResponse.json({ error: err?.message || 'Unknown error' }, { status: 500 });
  }
}

